import Animal.Animal;
import Animal.Birds.FLyable.Golub;
import Animal.Birds.FLyable.Leleka;
import Animal.Birds.FLyable.Orel;
import Animal.Birds.NonFLyable.Duck;
import Animal.Birds.NonFLyable.Kivi;
import Animal.Birds.NonFLyable.Pingvin;
import Animal.Birds.NonFLyable.Straus;
import Animal.Fish.Karas;
import Animal.Fish.Shuka;
import Animal.Fish.Som;
import Animal.Pet.Cat;
import Animal.Pet.Dog;
import Animal.Pet.Humster;
import Vehickle.ByRoad.Bus;
import Vehickle.ByRoad.Car;
import Vehickle.ByRoad.Tractor;
import Vehickle.BySky.AirBoll;
import Vehickle.BySky.Gvintokril;
import Vehickle.BySky.Litak;
import Vehickle.ByWater.Barja;
import Vehickle.ByWater.Kater;
import Vehickle.ByWater.Lodka;

public class Main {
    public static void main(String[] args){
        Duck duck = new Duck("Duck", "grey");
        duck.voice();
        duck.fly();
        duck.swim();
        Kivi kivi = new Kivi("Kivi", "yellow");
        kivi.voice();
        kivi.move();
        Pingvin pingvin = new Pingvin("Pingvin", "white");
        pingvin.voice();
        pingvin.swim();
        pingvin.move();
        Straus straus = new Straus("Straus", "grey");
        straus.voice();
        straus.move();
        Golub golub = new Golub("Golub", "grey");
        golub.voice();
        golub.fly();
        Leleka leleka = new Leleka("Leleka", "white");
        leleka.voice();
        leleka.fly();
        Orel orel = new Orel("Orel", "black");
        orel.voice();
        orel.fly();
        Karas karas = new Karas("Karas", "grey");
        karas.voice();
        karas.swim();
        Shuka shuka = new Shuka("Shuka", "black");
        shuka.voice();
        shuka.swim();
        Som som = new Som("Som", "yellow");
        som.voice();
        som.swim();
        Cat cat = new Cat("Cat", "white");
        cat.voice();
        cat.move();
        Dog dog = new Dog("Dog", "ginger");
        dog.voice();
        dog.move();
        Humster humster = new Humster("Humster", "white");
        humster.voice();
        humster.move();
        Bus bus = new Bus("Bus", "red");
        bus.noize();
        bus.move();
        Car car = new Car("Car", "black");
        car.noize();
        car.move();
        Tractor tractor = new Tractor("Tractor", "purple");
        tractor.noize();
        tractor.move();
        AirBoll airboll = new AirBoll("Airboll", "white");
        airboll.noize();
        airboll.fly();
        Gvintokril gvintokril = new Gvintokril("Gvintokril", "white");
        gvintokril.noize();
        gvintokril.fly();
        Litak litak = new Litak("Litak", "black");
        litak.noize();
        litak.fly();
        Barja barja = new Barja("Barja", "color");
        barja.noize();
        barja.swim();
        Kater kater = new Kater("Kater", "white");
        kater.noize();
        kater.swim();
        Lodka lodka = new Lodka("Lodka", "blue");
        lodka.noize();
        lodka.swim();
    }
}
